### ISSUE TITLE
Context files do not seem to be available.

### ISSUE THREAD

**Issue by carlkesselman** [dcppc/crosscut-metadata#17]
We are trying to read the JSON-LD using rdflib in python.  We get an error that seems to be caused by the fact that the context files are not available.  For example:

["https://w3id.org/dats/context/sdo/material_context.jsonld]("https://w3id.org/dats/context/sdo/material_context.jsonld)

Results in a 404 error.

**Comment by jonathancrabtree** [comment]
Looks like I screwed up the URIs and the DATS validator didn't catch it. This will be corrected in v0.4.

**Comment by agbeltran** [comment]
The correct URI is https://w3id.org/dats/context/sdo/material_sdo_context.jsonld

**Comment by robes** [comment]
As I noted in my email to the kc7 list, this appears to remain an open issue for the 3 released .json datasets.

**Comment by agbeltran** [comment]
This has been corrected on the v0.4 preview (https://github.com/dcppc/crosscut-metadata/tree/master/sparql), and it will be corrected in future DATS JSON-LD instances.

**Comment by jonathancrabtree** [comment]
Fixed in yesterday's v0.4 release but please see the README.md in https://github.com/dcppc/crosscut-metadata/tree/master/sparql regarding the advisability of using remote context file URIs in conjunction with the RDFLib JSON-LD parser plugin.
