### ISSUE TITLE
Where is the TOPMed dats file?

### ISSUE THREAD

**Issue by bheavner** [dcppc/crosscut-metadata#2]
I don't see `data/datasets/TOPMed_phs000946_wgs_public.json` in this repo.

**Comment by jonathancrabtree** [comment]
Hi Ben,

As a result of our eagerness to BDBag everything it is somewhat buried. You can find the file in the v0.2 cross-cut metadata BDBag (a .tar.gz file) in https://github.com/dcppc-phosphorous/crosscut-metadata/tree/master/releases 

For ease of access I've also placed a copy of the current public DATS JSON files in https://github.com/dcppc-phosphorous/crosscut-metadata/tree/master/dats-json, so you can now find it there too, albeit gzipped.

There is another top-level directory in this repo, https://github.com/dcppc-phosphorous/crosscut-metadata/tree/master/dats-json-examples, which contains the DATS JSON example files (produced by Philippe and others in the Oxford group) on which I based the TOPMed/dbGaP to DATS transformation code. The current instance is limited in scope (to phs000946) and contains only a single synthetic subject and sample created from the public variable summaries. To get the "real" instance for this study you'd have to run the script on both the public and protected dbGaP metadata files. The cross-cut release notes discuss this in greater detail but I'll also update the top-level README.md in this repo to try to make it more clear.
