### ISSUE TITLE
DATS Material 'derivesFrom' relationships needed

### ISSUE THREAD

**Issue by robes** [dcppc/crosscut-metadata#23]
We (Team Argon and presumably other downstream users of the datasets) need the derivesFrom predicate available in the datasets so that we can query for all three levels of the extract - sample - subject/donor hierarchy.

**Comment by proccaserra** [comment]
@robes this will addressed when we switch to using the OBOfoundry based context file.

https://github.com/datatagsuite/context/blob/master/obo/material_obo_context.jsonld

with dats.derives_from attributes mapped to RO_0001000

**Comment by jonathancrabtree** [comment]
This has been implemented and the queries in https://github.com/dcppc/crosscut-metadata/blob/master/sparql/topmed_gtex_sparql_examples.py, which make use of obo:RO_0001000 ("derives from") will work on the v0.4 DATS JSON files.
