### ISSUE TITLE
DATS Material 'characteristics' and 'extraProperties' needed

### ISSUE THREAD

**Issue by robes** [dcppc/crosscut-metadata#24]
We (Team Argon and presumably other downstream users of the datasets) need the 'characteristics' and 'extraProperties' predicates available in the datasets so that we can query for detailed properties of DATS Material subjects.

**Comment by jonathancrabtree** [comment]
All the relevant subject and sample information is now (in v0.4 and later) encoded as DATS characteristics, and the extraProperties have been effectively deprecated.
