### ISSUE TITLE
Dataset hierarchy harmonization

### ISSUE THREAD

**Issue by robes** [dcppc/crosscut-metadata#26]
As noted in the readme, we (Team Argon) would greatly benefit from harmonization of the Dataset hierarchy between the various (e.g., GTEx and TOPMed) datasets. We would support the suggestion made on the README to introduce a top level for the dataset (GTEx?) that does not naturally have one.

**Comment by jonathancrabtree** [comment]
Reopening due to validation failure in pre-release testing.
