### ISSUE TITLE
Sample query script(s) demonstrating all properties that are properly serialized in the datasets

### ISSUE THREAD

**Issue by robes** [dcppc/crosscut-metadata#27]
It would really help speed our work (especially with the deadlines closing in on us) the very nice samples that you have started in the `sparql/` subdirectory of the repository could be expanded with at least basic queries showing how to extract all of the properties that are available and properly serialized.

**Comment by jonathancrabtree** [comment]
Will do. This depends on the multiple context file solution to the 'derivesFrom' problem that @agbeltran is working on and which we hope to have resolved very very soon.
