### ISSUE TITLE
use of dats.Dimensions instead of dats.Extra properties when parsing dbGAP Data Dictionary

### ISSUE THREAD

**Issue by proccaserra** [dcppc/crosscut-metadata#29]
in https://github.com/dcppc/crosscut-metadata/blob/master/sparql/TOPMed_phs000946_wgs_public_v0.4preview2.jsonld
I noticed that some topmed study variables are declared as dimensions, others as extra-Properties.

in the transformation code
https://github.com/dcppc/crosscut-metadata/blob/master/ccmm/topmed/dna_extracts.py
line 123 seems to create all these extra-properties.

Mapping all entries found in 
ftp://ftp.ncbi.nlm.nih.gov/dbgap/studies/phs000946/phs000946.v3.p1/pheno_variable_summaries/phs000946.v3.pht005719.v1.TOPMed_WGS_Boston_EO_COPD_Subject_Phenotypes.data_dict.xml
to Dats.dimension would be better.

Also, possibly filtering out information about 'funding' and 'sequencing center'

**Comment by jonathancrabtree** [comment]
See https://github.com/dcppc/crosscut-metadata/blob/master/sparql/TOPMed_phs000946_wgs_public_v0.4preview3.jsonld and the updated queries in https://github.com/dcppc/crosscut-metadata/blob/master/sparql/topmed_sparql_examples.py.

It's done for the public metadata but not yet the access-restricted (meta)data. I also haven't filtered out anything, as you can see from the SPARQL output.

**Comment by jonathancrabtree** [comment]
Access-restricted metadata should now be handled in a similar fashion.
