### ISSUE TITLE
Demonstrate JSON-LD > RDF > SPARQL

### ISSUE THREAD

**Issue by david4096** [dcppc/crosscut-metadata#3]
It was discussed on the call that some of the context items needed to be relabeled in order to make the DATS format queryable from rdflib.

The use case in broad terms is to be able to make queryable the serialized data directly, either by loading into a triple store or locally.

To close this, a gist or python notebook might suffice!

**Comment by nemanjavuk** [comment]
Any updates on this? It would be really helpful to us, team Xenon.

**Comment by victor73** [comment]
Susanna and Michelle,

Can you both have a look and re-assign as necessary?

-Victor

**Comment by cmungall** [comment]
I notice some contexts don't resolve

E.g. in MGD_GRCm38-C57BL6J_public.json 

```
  "@context": "https://w3id.org/dats/context/sdo/dataset_context.jsonld",
```

redirects here which is 404 https://datatagsuite.github.io/context/sdo/dataset_context.jsonld

**Comment by agbeltran** [comment]
The actual resolvable URI is http://w3id.org/dats/context/sdo/dataset_sdo_context.jsonld

(even though we have sdo on the path, we decided that it is best to put it on the file name too to make it clear if the file is found on its own).

We can fix the `MGD_GRCm38-C57BL6J_public.json` file.

**Comment by david4096** [comment]
It was asked of me to flesh out this use case a little more.

We would like to index the DATS metadata, but we do not use a triple store. To index these metadata to match our data model, we must generate documents that can be individually indexed. These documents might be a "project" or "program" following the NCI dictionary.

I believe that to do this, we could write the JSON parsing ourselves, but that seems regressive when it is formatted as JSON-LD. We would like some SPARQL queries to generate flattened documents that match our data model. For example, we would like to know all the sample metadata from a dataset split into separate documents that can be indexed and searched.

Please let me know what else I can add!

**Comment by agbeltran** [comment]
Thanks @david4096 for providing more details. It would be great to discuss further about your use case. 

As discussed in the meeting last week, it would also be good to have a KC7 (or wider) survey on what is the best approach to provide this information, and check if most people would be interested on this approach.

**Comment by cmungall** [comment]
Helium is interested in this too. We will also likely have our own SPARQL transforms. cc @balhoff @putmantime (a lot of our team off on holiday at the moment so may be a bit before we respond fully)

**Comment by nsuvarnaiari** [comment]
@agbeltran @proccaserra @cmungall 
Right after you left to the airport on the second day of Portland Workshop, a decision was made to have a call in the week of 16th to discuss more on this (Jonathan - Team phosphorus, will be back by then). @david4096 volunteered to set up the call. David, are you still ok with it or you want me to take care of that?

Thanks
Suvvi

**Comment by david4096** [comment]
@nsuvarnaiari yep, putting together the invite email now. I'll also blast the KC7 group and link to this issue!

**Comment by agbeltran** [comment]
that's great - thanks for the update

**Comment by nemanjavuk** [comment]
@david4096 where to are you sending this email? I wouldn’t want to miss this talk :)

**Comment by david4096** [comment]
https://github.com/dcppc/crosscut-metadata/issues/11

**Comment by agbeltran** [comment]
The notebook with a small demo on using SPARQL queries over DATS JSON-LD and also a conversion to N3 format, as discussed in yesterday's call,  is here: https://github.com/datatagsuite/dats-tools/blob/master/notebooks/dats_agr.ipynb

I will provide a binder for online execution.

**Comment by agbeltran** [comment]
The notebook can now be executed through binder following this link:

https://mybinder.org/v2/gh/datatagsuite/dats-tools/master?filepath=notebooks%2Fdats_agr.ipynb

Also available in the README file at: https://github.com/datatagsuite/dats-tools
