### ISSUE TITLE
3rd level dataset (i.e., data files)

### ISSUE THREAD

**Issue by robes** [dcppc/crosscut-metadata#33]
This may be a 'question' or an issue. I am trying to query the file information and I can see that its in there by modifying the sample query for extracts/samples/subjects. For example:

```
            """
            SELECT DISTINCT ?dataset_id ?rna_or_dna_extract
            WHERE {
                ?dataset a obo:IAO_0000100.
                ?mat1 a obo:BFO_0000040.
                ?dataset obo:IAO_0000136 ?mat1.
                ?mat1 obo:IAO_0000590 ?rna_or_dna_extract.
                ?mat1 obo:BFO_0000023 ?role.
                ?role sdo:value ?rolename.
                ?mat1 obo:RO_0001000 ?sample.
                ?sample obo:IAO_0000300 ?sample_name.
                ?sample obo:RO_0001000 ?subject.
                ?subject obo:IAO_0000300 ?subject_name.
                FILTER ((str(?rolename) = "DNA extract") || (str(?rolename) = "RNA extract")).
                ?dataset obo:IAO_0000577 ?dataset_identifier.
                ?dataset_identifier sdo:identifier ?dataset_id.
            }
            """
```

By adding the last couple triple patterns to the where clause and projecting the `dataset_id`, I get rows of results like:

```
dataset_id, rna_or_dna_extract
GTEx_Analysis_2016-01-15_v7_RNA-SEQ_GTEx_Analysis_2016-01-15_v7_STARv2.4.2a_junctions.gct.gz, RNA from GTEX-111CU-0626-SM-5EGHL
GTEx_Analysis_2016-01-15_v7_RNA-SEQ_GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct.gz, RNA from GTEX-111CU-0626-SM-5EGHL
GTEx_Analysis_2016-01-15_v7_RNA-SEQ_GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_tpm.gct.gz, RNA from GTEX-111CU-0626-SM-5EGHL
GTEx_Analysis_2016-01-15_v7_RNA-SEQ_GTEx_Analysis_2016-01-15_v7_RSEMv1.2.22_transcript_tpm.txt.gz, RNA from GTEX-111CU-0626-SM-5EGHL
GTEx_Analysis_2016-01-15_v7_RNA-SEQ_GTEx_Analysis_2016-01-15_v7_RSEMv1.2.22_transcript_expected_count.txt.gz, RNA from GTEX-111CU-0626-SM-5EGHL
...
```

So I can see that there are "datsets" representing the files, I believe. (Side note: I changed the formatting of output to be more CSV like for my personal use. Ignore that.)

I thought I could go back to your first original sample query and get the 3rd level of the dataset hierarchy (i.e., top_dataset, dataset, and then data file). Like this:

```
        """
        SELECT DISTINCT ?ident ?title
        WHERE {
            ?top_dataset a obo:IAO_0000100.
            ?top_dataset obo:OBI_0001622 ?top_title.
            ?top_dataset obo:BFO_0000051 ?dataset.
            ?dataset a obo:IAO_0000100.
            ?dataset obo:OBI_0001622 ?title.
            ?dataset obo:IAO_0000577 ?identifier.
            ?identifier sdo:identifier ?ident.
            FILTER ((str(?top_title) = "Genotype-Tissue Expression Project (GTEx)") || (str(?top_title) = "Trans-Omics for Precision Medicine (TOPMed)")).
            ?dataset obo:BFO_0000051 ?file.
        }
        """
```

Above I simply added a triple pattern to the where clause to go from the `?dataset` to its "has part" (BFO_0000051) `?file`.

However, this yields 0 results. Did I do it wrong? Did I misunderstand the model? Or is it not encoded yet in the jsonld? All of the above? :-) 

SIDE ISSUE: in the prior query where I extended the extract/sample/subject query to get the dataset (file), the filename is coded as the sdo:identifier of the file/dataset. Is that just a short-term hack to get by for now? Seems like long-term that wouldn't be a unique identifier.

Thanks

**Comment by jonathancrabtree** [comment]
Which DATS file are you running the second query on? When I run the query (on the v0.4 GTEx_v7_rnaseq_20_SAMPLES_public.jsonld) , adding "?file" to the SELECT clause, but changing nothing else, I get what I think is the expected result:

    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/03tv-bg44
    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/1j6e-y291
    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/t9mt-na55
    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/z0zt-1366
    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/xeab-fn88
    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/zzv1-xb48
    GTEx_Analysis_2016-01-15_v7_RNA-SEQ     GTEx v7 RNA-Seq Analysis        https://doi.org/10.25491/j0aj-4w78

The first two columns refer to the 2nd level Dataset and the third is the JSON-LD id of the "?file", which for these public files RNA-Seq files from the GTEx Portal are the KC2-produced DOIs.

As for the filename encoding, yes, I think that is a short-term solution. An updated encoding for file-level data was proposed here:

https://github.com/dcppc/crosscut-metadata/blob/master/dats-json-examples/DATS-datafiles-haspart-dataset-activity-pattern.json

v0.5 will look more like this, with each (file-level) Dataset linked to two DatasetDistributions, one for the S3 copy of the file and one for the GCP copy of the file. The S3 or GCP/GS URI will be in the "landingPage" and also used as the JSON-LD id of the DatasetDistribution.

**Comment by robes** [comment]
Thanks! That worked for me. I was using the same input file but didn't include `?file` in the projection. So I guess the only 'issue' here if any would be to have a sample query in the sparql folder.

**Comment by robes** [comment]
Actually, next question... The DOI (in the `?file` field) is resolvable to a landing page for the data file. Is that the only resolvable URL that I should expect for the files in the DATS bundle? thx

**Comment by robes** [comment]
Sorry, you answered this above.
