### ISSUE TITLE
Add KC2-generated GUIDs/DOIs to controlled-access metadata instance.

### ISSUE THREAD

**Issue by jonathancrabtree** [dcppc/crosscut-metadata#34]
KC2 is working on generating DOIs for the GTEx and TOPMed pilot phase data files, specifically the .cram and .crai sequence files referenced in two of the GTEx manifest files in the following public GitHub repo:

https://github.com/dcppc/data-stewards/tree/master/gtex/v7/manifests/protected_data/

In that repo there are 12766 .cram and 12766 .crai file URIs in the RNA-Seq manifest file:

rnaseq_cram_files_v7_dbGaP_011516.txt

and 652 .cram and 652 .crai files in the WGS manifest file:

wgs_cram_files_v7_hg38_datacommons_011516.txt

For TOPMed the central manifest file (manifest.data-commons-pilot.txt, the contents of which were discussed in https://github.com/dcppc/data-stewards/issues/26 ) on the Google Storage bucket contains 10838 .cram files (plus 10838 .crai files) and 10245 .vcf.gz files (plus 10245 .vcf.gz.csi files).  

DOIs have been (or will be) generated for each of the aforementioned .cram and .vcf.gz files, in addition to their associated .crai and .vcf.gz.csi index files. These DOIs will be incorporated into the controlled-access crosscut metadata model instances for GTEx and TOPMed (and potentially also the public GTEx instance). The sequence data files are currently referenced within the DATS `DatasetDistributions` that are associated with the DATS `Dataset` that corresponds to the output of a specific sequencing run. For example, there is a `Dataset` that corresponds to the .cram file for the WGS sequences generated from sample X, collected from body site B of subject S. That `Dataset` links to two `DatasetDistributions`, one for the S3 copy of the file and the other for the GS copy of the file. Pending a more specific extension to the DATS standard the accompanying .crai index file is currently included among the DATS `relatedIdentifiers` of the `DatasetDistribution`.

**Comment by mfenner** [comment]
Team Sodium has now registered the following DOIs:

## GTEx (26,859 DOIs)

* 23 DOIs for public data files
* 12,766 DOIs each for the protected data .cram and .crai rna-seq files
* 652 DOIs each for the protected data .cram and .crai wgs files

The mapping file name to DOI and core metadata in schema.org JSON-LD for protected data were added as pull request to https://github.com/dcppc/data-stewards

## TopMed (42,380 DOIs)

* 107 DOIs each for the public data .cram and .crai files
* 10,838 DOIs each for the protected data .cram and .crai files
* 10,245 DOIs each for the protected data .vcf and .vcf.csi files

The mapping file name to DOI and core metadata in schema.org JSON-LD for protected data were added as pull request to https://github.com/dcppc/full-stacks

We did register core metadata for each DOI, which includes the checksum and in many cases file size, but not the contentURL.

**Comment by jonathancrabtree** [comment]
The public v0.7 release of 2 days ago includes the GTEx DOIs:

https://github.com/dcppc/crosscut-metadata/tree/master/releases

An equivalent controlled-access release is in preparation.

**Comment by jonathancrabtree** [comment]
The controlled-access v0.7 release has also been updated.
